name: mouth-driver-hardware-tests
labels:
  - docker-image
  - hardware
dependencies:
type: test
steps:
  - job: hardware-test-suite
    steps:
      - test-name: hw-mouth
        cmds-to-run-in-cli:
          - "artie-cli driver self-check -n mouth-driver --artie-profile /hardware_test_profile.json"
        expected-results:
          FW: "working"
          LED: "working"
          LCD: "working"
