name: eyebrows-driver-hardware-tests
labels:
  - docker-image
  - hardware
dependencies:
type: test
steps:
  - job: hardware-test-suite
    steps:
      - test-name: hw-eyebrows
        cmds-to-run-in-cli:
          - "artie-cli driver self-check -n eyebrows-driver --artie-profile /hardware_test_profile.json"
        expected-results:
          FW: "working"
          LED-LEFT: "working"
          LED-RIGHT: "working"
          LCD-LEFT: "working"
          LCD-RIGHT: "working"
          LEFT-SERVO: "working"
          RIGHT-SERVO: "working"
