name: eyebrows-driver-unit-tests
labels:
  - docker-image
  - unit
dependencies:
  - driver-eyebrows: docker-image
  - artie-cli: docker-image
type: test
steps:
  - job: single-container-cli-suite
    docker-image-under-test:
      dependency:
        name: docker-image
        producing-task: driver-eyebrows
    cmd-to-run-in-dut: "python -m src.main /conf/mcu-fw.elf --port 18863 --loglevel info"
    dut-port-mappings:
      - 18863: 18863
    cli-image:
      dependency:
        name: docker-image
        producing-task: artie-cli
    steps:
      - test-name: init-mcu
        cmd-to-run-in-cli: "artie-cli help"
        expected-outputs:
          - what: "Mocking MCU FW load."
            where: ${DUT}
      - test-name: led-get
        cmd-to-run-in-cli: "artie-cli status-led get eyebrow-left -n eyebrows-driver --unit-test --port 18863 --artie-profile /unit_test_profile.json"
        expected-outputs:
          - what: "LED -> State: heartbeat"
            where: ${DUT}
      - test-name: led-set-on
        cmd-to-run-in-cli: "artie-cli status-led set eyebrow-left on -n eyebrows-driver --unit-test --port 18863 --artie-profile /unit_test_profile.json"
        expected-outputs:
          - what: "left LED -> ON"
            where: ${DUT}
      - test-name: led-set-off
        cmd-to-run-in-cli: "artie-cli status-led set eyebrow-right off -n eyebrows-driver --unit-test --port 18863 --artie-profile /unit_test_profile.json"
        expected-outputs:
          - what: "right LED -> OFF"
            where: ${DUT}
      - test-name: led-set-heartbeat
        cmd-to-run-in-cli: "artie-cli status-led set eyebrow-left heartbeat -n eyebrows-driver --unit-test --port 18863 --artie-profile /unit_test_profile.json"
        expected-outputs:
          - what: "left LED -> HEARTBEAT"
            where: ${DUT}
      - test-name: display-get
        cmd-to-run-in-cli: "artie-cli display get eyebrow-right -n eyebrows-driver --unit-test --port 18863 --artie-profile /unit_test_profile.json"
        expected-outputs:
          - what: "right eyebrow LCD -> State: ['M', 'H', 'M']"
            where: ${DUT}
      - test-name: display-test
        cmd-to-run-in-cli: "artie-cli display test eyebrow-right -n eyebrows-driver --unit-test --port 18863 --artie-profile /unit_test_profile.json"
        expected-outputs:
          - what: "right LCD -> TEST"
            where: ${DUT}
      - test-name: display-clear
        cmd-to-run-in-cli: "artie-cli display clear eyebrow-left -n eyebrows-driver --unit-test --port 18863 --artie-profile /unit_test_profile.json"
        expected-outputs:
          - what: "left LCD -> OFF"
            where: ${DUT}
      - test-name: display-set
        cmd-to-run-in-cli: "artie-cli display set eyebrow-left SGhITAo= -n eyebrows-driver --unit-test --port 18863 --artie-profile /unit_test_profile.json"
        expected-outputs:
          - what: "left LCD -> DRAW"
            where: ${DUT}
      - test-name: mcu-reload-fw
        cmd-to-run-in-cli: "artie-cli mcu reload-fw eyebrow-left -n eyebrows-driver --unit-test --port 18863 --artie-profile /unit_test_profile.json"
        expected-outputs:
          - what: "Mocking MCU FW load."
            where: ${DUT}
      - test-name: servo-get-position
        cmd-to-run-in-cli: "artie-cli servo get eyebrow-right -n eyebrows-driver --unit-test --port 18863 --artie-profile /unit_test_profile.json"
        expected-outputs:
          - what: "right servo position -> 90.00"
            where: ${DUT}
      - test-name: servo-set-position
        cmd-to-run-in-cli: "artie-cli servo set eyebrow-right 45 -n eyebrows-driver --unit-test --port 18863 --artie-profile /unit_test_profile.json"
        expected-outputs:
          - what: "right SERVO -> GO"
            where: ${DUT}
      - test-name: driver-self-check
        cmd-to-run-in-cli: "artie-cli driver self-check -n eyebrows-driver --unit-test --port 18863 --artie-profile /unit_test_profile.json"
        expected-outputs:
          - what: "Checking FW subsystem..."
            where: ${DUT}
          - what: "Checking LED subsystem..."
            where: ${DUT}
          - what: "Checking LCD subsystem..."
            where: ${DUT}
          - what: "Checking servo subsystem..."
            where: ${DUT}
