name: custom
labels:
  - container-set
dependencies:
cli-args:
  - name: --release-name
    default: null
    help: "The name of the Helm release. If not specified, defaults to 'artie-custom'."
artifacts:
  - name: artie-base
    type: helm-chart
type: deploy
steps:
  - job: add
    what: artie-custom
    chart: deploy-files/artie-base
